name: Running bot
 
on: [push]

env:
  BOTUN: S
  BOTKEY: 1
  USERKEY: 12
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison ccache openjdk-8-jdk
       - name: Setup 2.0
         run: |
            git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs ErfanGSIs
            sudo chmod -R 0777 ErfanGSIs
            sudo bash ErfanGSIs/setup.sh
            
       - name: Download BoboBot source
         run: |
            sudo wget https://github.com/VegaBobo/Bot3/releases/download/v0.1/BoboBot.jar
            
       - name: Generate values
         run: java -jar BoboBot.jar
         
       - name: Add values
         run: |
             rm -rf configs/config.prop
             cd configs
             touch config.prop
             echo "#Bo³+t config file" >> "config.prop"
             echo "#Fri Jun 26 06:08:12 UTC 2020" >> "config.prop"
             echo "bot-username=ruigsibuilderbot" >> "config.prop"
             echo "bot-token=${{ secrets.TOKEN }}" >> "config.prop"
             echo "bot-master=${{ secrets.CHAT_ID }} " >> "config.prop"
             
       - name: Run bobobot
         run: sudo java -jar BoboBot.jar
         
            
